// <auto-generated />
using System;
using Deep.Programs.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Deep.Programs.Data.Migrations
{
    [DbContext(typeof(ProgramsDbContext))]
    partial class ProgramsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("programs")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Deep.Programs.Domain.ProgramAssignments.ProgramAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_program_assignments");

                    b.HasIndex("ProgramId")
                        .HasDatabaseName("ix_program_assignments_program_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_program_assignments_user_id");

                    b.HasIndex("ProgramId", "UserId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ix_program_assignments_program_id_user_id_role");

                    b.ToTable("program_assignments", "programs");
                });

            modelBuilder.Entity("Deep.Programs.Domain.Programs.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("ProgramStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("program_status");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_programs");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_programs_owner_id");

                    b.ToTable("programs", "programs");
                });

            modelBuilder.Entity("Deep.Programs.Domain.Programs.ProgramProduct", b =>
                {
                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<string>("ProductName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.HasKey("ProgramId", "ProductName")
                        .HasName("pk_program_products");

                    b.ToTable("program_products", "programs");
                });

            modelBuilder.Entity("Deep.Programs.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "programs");
                });

            modelBuilder.Entity("Deep.Programs.Domain.ProgramAssignments.ProgramAssignment", b =>
                {
                    b.HasOne("Deep.Programs.Domain.Programs.Program", null)
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_program_assignments_programs_program_id");

                    b.HasOne("Deep.Programs.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_program_assignments_users_user_id");
                });

            modelBuilder.Entity("Deep.Programs.Domain.Programs.ProgramProduct", b =>
                {
                    b.HasOne("Deep.Programs.Domain.Programs.Program", null)
                        .WithMany("Products")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_program_products_programs_program_id");
                });

            modelBuilder.Entity("Deep.Programs.Domain.Programs.Program", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
