// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Vast.Programs.Data.Migrations;

/// <inheritdoc />
public partial class AddProgramProducts : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.RenameColumn(
            name: "type",
            schema: "programs",
            table: "program_assignments",
            newName: "role"
        );

        migrationBuilder.RenameIndex(
            name: "ix_program_assignments_program_id_user_id_type",
            schema: "programs",
            table: "program_assignments",
            newName: "ix_program_assignments_program_id_user_id_role"
        );

        migrationBuilder.AddColumn<bool>(
            name: "is_active",
            schema: "programs",
            table: "program_assignments",
            type: "boolean",
            nullable: false,
            defaultValue: false
        );

        migrationBuilder.CreateTable(
            name: "program_products",
            schema: "programs",
            columns: table => new
            {
                program_id = table.Column<Guid>(type: "uuid", nullable: false),
                product_name = table.Column<string>(
                    type: "character varying(200)",
                    maxLength: 200,
                    nullable: false
                ),
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_program_products", x => new { x.program_id, x.product_name });
                table.ForeignKey(
                    name: "fk_program_products_programs_program_id",
                    column: x => x.program_id,
                    principalSchema: "programs",
                    principalTable: "programs",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade
                );
            }
        );
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(name: "program_products", schema: "programs");

        migrationBuilder.DropColumn(
            name: "is_active",
            schema: "programs",
            table: "program_assignments"
        );

        migrationBuilder.RenameColumn(
            name: "role",
            schema: "programs",
            table: "program_assignments",
            newName: "type"
        );

        migrationBuilder.RenameIndex(
            name: "ix_program_assignments_program_id_user_id_role",
            schema: "programs",
            table: "program_assignments",
            newName: "ix_program_assignments_program_id_user_id_type"
        );
    }
}
