// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Vast.Accounts.Application.Data.Migrations;

/// <inheritdoc />
public partial class AuditLogs : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "audit_logs",
            schema: "accounts",
            columns: table => new
            {
                id = table.Column<Guid>(type: "uuid", nullable: false),
                user_id = table.Column<Guid>(type: "uuid", nullable: true),
                audit_type = table.Column<int>(type: "integer", nullable: false),
                table_name = table.Column<string>(
                    type: "character varying(256)",
                    maxLength: 256,
                    nullable: false
                ),
                primary_key = table.Column<string>(type: "text", nullable: false),
                old_values = table.Column<string>(type: "text", nullable: true),
                new_values = table.Column<string>(type: "text", nullable: true),
                changed_columns = table.Column<string>(type: "text", nullable: true),
                occurred_at_utc = table.Column<DateTime>(
                    type: "timestamp with time zone",
                    nullable: false
                ),
            },
            constraints: table => table.PrimaryKey("pk_audit_logs", x => x.id)
        );

        migrationBuilder.CreateIndex(
            name: "ix_audit_logs_occurred_at_utc",
            schema: "accounts",
            table: "audit_logs",
            column: "occurred_at_utc"
        );

        migrationBuilder.CreateIndex(
            name: "ix_audit_logs_table_name",
            schema: "accounts",
            table: "audit_logs",
            column: "table_name"
        );

        migrationBuilder.CreateIndex(
            name: "ix_audit_logs_user_id",
            schema: "accounts",
            table: "audit_logs",
            column: "user_id"
        );
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder) =>
        migrationBuilder.DropTable(name: "audit_logs", schema: "accounts");
}
