// <auto-generated />
using System;
using Vast.Accounts.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Vast.Accounts.Application.Data.Migrations
{
    [DbContext(typeof(AccountsDbContext))]
    [Migration("20260228080355_AuditLogs")]
    partial class AuditLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("accounts")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountRole", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("RolesName")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("AccountId", "RolesName")
                        .HasName("pk_account_roles");

                    b.HasIndex("RolesName")
                        .HasDatabaseName("ix_account_roles_roles_name");

                    b.ToTable("account_roles", "accounts");
                });

            modelBuilder.Entity("Vast.Accounts.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("security_stamp");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_email");

                    b.ToTable("accounts", "accounts");
                });

            modelBuilder.Entity("Vast.Accounts.Domain.Accounts.PasswordHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_password_histories");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_password_histories_account_id");

                    b.HasIndex("AccountId", "ChangedAtUtc")
                        .HasDatabaseName("ix_password_histories_account_id_changed_at_utc");

                    b.ToTable("password_histories", "accounts");
                });

            modelBuilder.Entity("Vast.Accounts.Domain.Accounts.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiryDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date_utc");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_password_reset_tokens_account_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_tokens_token");

                    b.ToTable("password_reset_tokens", "accounts");
                });

            modelBuilder.Entity("Vast.Accounts.Domain.Accounts.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.HasKey("Code")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", "accounts");

                    b.HasData(
                        new
                        {
                            Code = "account.register.itadmin"
                        },
                        new
                        {
                            Code = "account.register.programowner"
                        },
                        new
                        {
                            Code = "account.register.manager"
                        },
                        new
                        {
                            Code = "account.register.coordinator"
                        },
                        new
                        {
                            Code = "account.register.brandambassador"
                        },
                        new
                        {
                            Code = "account.read.coordinator"
                        },
                        new
                        {
                            Code = "account.read.programowner"
                        },
                        new
                        {
                            Code = "account.read.brandambassador"
                        },
                        new
                        {
                            Code = "account.read.manager"
                        },
                        new
                        {
                            Code = "account.read.itadmin"
                        },
                        new
                        {
                            Code = "programs.read.own"
                        },
                        new
                        {
                            Code = "programs.read.all"
                        },
                        new
                        {
                            Code = "programs.create"
                        },
                        new
                        {
                            Code = "programs.update"
                        },
                        new
                        {
                            Code = "programs.assign.coowner"
                        },
                        new
                        {
                            Code = "programs.assign.coordinator"
                        },
                        new
                        {
                            Code = "programs.assign.brandambassador"
                        });
                });

            modelBuilder.Entity("Vast.Accounts.Domain.Accounts.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiryDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date_utc");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_refresh_tokens_account_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.ToTable("refresh_tokens", "accounts");
                });

            modelBuilder.Entity("Vast.Accounts.Domain.Accounts.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Name")
                        .HasName("pk_roles");

                    b.ToTable("roles", "accounts");

                    b.HasData(
                        new
                        {
                            Name = "ItAdmin"
                        },
                        new
                        {
                            Name = "Manager"
                        },
                        new
                        {
                            Name = "ProgramOwner"
                        },
                        new
                        {
                            Name = "Coordinator"
                        },
                        new
                        {
                            Name = "BrandAmbassador"
                        });
                });

            modelBuilder.Entity("Vast.Common.Application.Auditing.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AuditType")
                        .HasColumnType("integer")
                        .HasColumnName("audit_type");

                    b.Property<string>("ChangedColumns")
                        .HasColumnType("text")
                        .HasColumnName("changed_columns");

                    b.Property<string>("NewValues")
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("OldValues")
                        .HasColumnType("text")
                        .HasColumnName("old_values");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_key");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("table_name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_audit_logs_occurred_at_utc");

                    b.HasIndex("TableName")
                        .HasDatabaseName("ix_audit_logs_table_name");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", "accounts");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<string>("PermissionCode")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission_code");

                    b.Property<string>("RoleName")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("PermissionCode", "RoleName")
                        .HasName("pk_role_permissions");

                    b.HasIndex("RoleName")
                        .HasDatabaseName("ix_role_permissions_role_name");

                    b.ToTable("role_permissions", "accounts");

                    b.HasData(
                        new
                        {
                            PermissionCode = "account.register.itadmin",
                            RoleName = "ItAdmin"
                        },
                        new
                        {
                            PermissionCode = "account.register.programowner",
                            RoleName = "ItAdmin"
                        },
                        new
                        {
                            PermissionCode = "account.register.manager",
                            RoleName = "ItAdmin"
                        },
                        new
                        {
                            PermissionCode = "account.read.manager",
                            RoleName = "ItAdmin"
                        },
                        new
                        {
                            PermissionCode = "account.read.itadmin",
                            RoleName = "ItAdmin"
                        },
                        new
                        {
                            PermissionCode = "account.read.programowner",
                            RoleName = "ItAdmin"
                        },
                        new
                        {
                            PermissionCode = "account.register.coordinator",
                            RoleName = "ProgramOwner"
                        },
                        new
                        {
                            PermissionCode = "account.read.coordinator",
                            RoleName = "ProgramOwner"
                        },
                        new
                        {
                            PermissionCode = "programs.read.own",
                            RoleName = "ProgramOwner"
                        },
                        new
                        {
                            PermissionCode = "programs.create",
                            RoleName = "ProgramOwner"
                        },
                        new
                        {
                            PermissionCode = "programs.update",
                            RoleName = "ProgramOwner"
                        },
                        new
                        {
                            PermissionCode = "programs.assign.coowner",
                            RoleName = "ProgramOwner"
                        },
                        new
                        {
                            PermissionCode = "programs.assign.coordinator",
                            RoleName = "ProgramOwner"
                        },
                        new
                        {
                            PermissionCode = "programs.read.all",
                            RoleName = "Manager"
                        },
                        new
                        {
                            PermissionCode = "account.register.brandambassador",
                            RoleName = "Coordinator"
                        },
                        new
                        {
                            PermissionCode = "account.read.brandambassador",
                            RoleName = "Coordinator"
                        },
                        new
                        {
                            PermissionCode = "programs.assign.brandambassador",
                            RoleName = "Coordinator"
                        },
                        new
                        {
                            PermissionCode = "programs.read.own",
                            RoleName = "BrandAmbassador"
                        });
                });

            modelBuilder.Entity("AccountRole", b =>
                {
                    b.HasOne("Vast.Accounts.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_roles_accounts_account_id");

                    b.HasOne("Vast.Accounts.Domain.Accounts.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_roles_roles_roles_name");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("Vast.Accounts.Domain.Accounts.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_code");

                    b.HasOne("Vast.Accounts.Domain.Accounts.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_name");
                });
#pragma warning restore 612, 618
        }
    }
}
