// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Deep.Programs.Application.Data.Migrations;

/// <inheritdoc />
public partial class AddRoleToProgramAssignment : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(
            name: "fk_program_products_programs_program_id",
            schema: "programs",
            table: "program_products"
        );

        migrationBuilder.DropIndex(
            name: "ix_program_assignments_program_id_user_id_role",
            schema: "programs",
            table: "program_assignments"
        );

        migrationBuilder.DropPrimaryKey(
            name: "pk_program_products",
            schema: "programs",
            table: "program_products"
        );

        migrationBuilder.DropColumn(name: "role", schema: "programs", table: "users");

        migrationBuilder.DropColumn(name: "role", schema: "programs", table: "program_assignments");

        migrationBuilder.RenameTable(
            name: "program_products",
            schema: "programs",
            newName: "program_product",
            newSchema: "programs"
        );

        migrationBuilder.AddColumn<string>(
            name: "role_name",
            schema: "programs",
            table: "program_assignments",
            type: "character varying(50)",
            maxLength: 50,
            nullable: false,
            defaultValue: ""
        );

        migrationBuilder.AddPrimaryKey(
            name: "pk_program_product",
            schema: "programs",
            table: "program_product",
            columns: new[] { "program_id", "product_name" }
        );

        migrationBuilder.CreateTable(
            name: "roles",
            schema: "programs",
            columns: table => new
            {
                name = table.Column<string>(
                    type: "character varying(50)",
                    maxLength: 50,
                    nullable: false
                ),
            },
            constraints: table => table.PrimaryKey("ak_role_name", x => x.name)
        );

        migrationBuilder.CreateTable(
            name: "user_roles",
            schema: "programs",
            columns: table => new
            {
                role_name = table.Column<string>(type: "character varying(50)", nullable: false),
                user_id = table.Column<Guid>(type: "uuid", nullable: false),
            },
            constraints: table =>
            {
                table.PrimaryKey("pk_user_roles", x => new { x.role_name, x.user_id });
                table.ForeignKey(
                    name: "fk_user_roles_roles_roles_name",
                    column: x => x.role_name,
                    principalSchema: "programs",
                    principalTable: "roles",
                    principalColumn: "name",
                    onDelete: ReferentialAction.Cascade
                );
                table.ForeignKey(
                    name: "fk_user_roles_users_user_id",
                    column: x => x.user_id,
                    principalSchema: "programs",
                    principalTable: "users",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Cascade
                );
            }
        );

        migrationBuilder.InsertData(
            schema: "programs",
            table: "roles",
            column: "name",
            values: new object[]
            {
                "BrandAmbassador",
                "Coordinator",
                "ItAdmin",
                "Manager",
                "ProgramOwner",
            }
        );

        migrationBuilder.CreateIndex(
            name: "ix_program_assignments_program_id_user_id_role_name",
            schema: "programs",
            table: "program_assignments",
            columns: new[] { "program_id", "user_id", "role_name" },
            unique: true
        );

        migrationBuilder.CreateIndex(
            name: "ix_program_assignments_role_name",
            schema: "programs",
            table: "program_assignments",
            column: "role_name"
        );

        migrationBuilder.CreateIndex(
            name: "ix_user_roles_user_id",
            schema: "programs",
            table: "user_roles",
            column: "user_id"
        );

        migrationBuilder.AddForeignKey(
            name: "fk_program_assignments_role_role_name",
            schema: "programs",
            table: "program_assignments",
            column: "role_name",
            principalSchema: "programs",
            principalTable: "roles",
            principalColumn: "name",
            onDelete: ReferentialAction.Restrict
        );

        migrationBuilder.AddForeignKey(
            name: "fk_program_product_programs_program_id",
            schema: "programs",
            table: "program_product",
            column: "program_id",
            principalSchema: "programs",
            principalTable: "programs",
            principalColumn: "id",
            onDelete: ReferentialAction.Cascade
        );
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropForeignKey(
            name: "fk_program_assignments_role_role_name",
            schema: "programs",
            table: "program_assignments"
        );

        migrationBuilder.DropForeignKey(
            name: "fk_program_product_programs_program_id",
            schema: "programs",
            table: "program_product"
        );

        migrationBuilder.DropTable(name: "user_roles", schema: "programs");

        migrationBuilder.DropTable(name: "roles", schema: "programs");

        migrationBuilder.DropIndex(
            name: "ix_program_assignments_program_id_user_id_role_name",
            schema: "programs",
            table: "program_assignments"
        );

        migrationBuilder.DropIndex(
            name: "ix_program_assignments_role_name",
            schema: "programs",
            table: "program_assignments"
        );

        migrationBuilder.DropPrimaryKey(
            name: "pk_program_product",
            schema: "programs",
            table: "program_product"
        );

        migrationBuilder.DropColumn(
            name: "role_name",
            schema: "programs",
            table: "program_assignments"
        );

        migrationBuilder.RenameTable(
            name: "program_product",
            schema: "programs",
            newName: "program_products",
            newSchema: "programs"
        );

        migrationBuilder.AddColumn<string>(
            name: "role",
            schema: "programs",
            table: "users",
            type: "text",
            nullable: false,
            defaultValue: ""
        );

        migrationBuilder.AddColumn<string>(
            name: "role",
            schema: "programs",
            table: "program_assignments",
            type: "text",
            nullable: false,
            defaultValue: ""
        );

        migrationBuilder.AddPrimaryKey(
            name: "pk_program_products",
            schema: "programs",
            table: "program_products",
            columns: new[] { "program_id", "product_name" }
        );

        migrationBuilder.CreateIndex(
            name: "ix_program_assignments_program_id_user_id_role",
            schema: "programs",
            table: "program_assignments",
            columns: new[] { "program_id", "user_id", "role" },
            unique: true
        );

        migrationBuilder.AddForeignKey(
            name: "fk_program_products_programs_program_id",
            schema: "programs",
            table: "program_products",
            column: "program_id",
            principalSchema: "programs",
            principalTable: "programs",
            principalColumn: "id",
            onDelete: ReferentialAction.Cascade
        );
    }
}
